ktor:
  application:
    modules:
      - com.juliusyam.ApplicationKt.module
  deployment:
    port: 8080
db:
  mongo:
    user: "mongo"
    password: "mysecretpassword"
    host: "localhost"
    port: "27017"
    database:
      name: "mongo"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
