ktor:
  application:
    modules:
      - com.juliusyam.ApplicationKt.module
  deployment:
    port: 8081
db:
  mongo:
    user: "mongo"
    password: "mysecretpassword"
    host: "mongodb"
    port: "27017"
    database:
      name: "mongo"
jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8081/"
  audience: "http://0.0.0.0:8081/"
  realm: "Snow Park Tracking - Ktor"
